// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pzDatabase.model;

namespace pzDatabase.Migrations
{
    [DbContext(typeof(applicationDbContext))]
    [Migration("20210210015640_AgregandoOtrasTablas")]
    partial class AgregandoOtrasTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ingredientepizza", b =>
                {
                    b.Property<int>("ingredienteid")
                        .HasColumnType("int");

                    b.Property<int>("pizzaid")
                        .HasColumnType("int");

                    b.HasKey("ingredienteid", "pizzaid");

                    b.HasIndex("pizzaid");

                    b.ToTable("ingredientepizza");
                });

            modelBuilder.Entity("pzDatabase.model.detallePedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("idPizza")
                        .HasColumnType("int");

                    b.Property<int>("subtotal")
                        .HasColumnType("int");

                    b.Property<int>("tamaño")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("detallePedido");
                });

            modelBuilder.Entity("pzDatabase.model.factura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("formaDePago")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("factura");
                });

            modelBuilder.Entity("pzDatabase.model.ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("ingrediente");
                });

            modelBuilder.Entity("pzDatabase.model.pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("demora")
                        .HasColumnType("int");

                    b.Property<int?>("detallePedidoid")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<int?>("facturaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("detallePedidoid");

                    b.HasIndex("facturaid");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("pzDatabase.model.pizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("pizza");
                });

            modelBuilder.Entity("ingredientepizza", b =>
                {
                    b.HasOne("pzDatabase.model.ingrediente", null)
                        .WithMany()
                        .HasForeignKey("ingredienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pzDatabase.model.pizza", null)
                        .WithMany()
                        .HasForeignKey("pizzaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pzDatabase.model.pedido", b =>
                {
                    b.HasOne("pzDatabase.model.detallePedido", null)
                        .WithMany("pedido")
                        .HasForeignKey("detallePedidoid");

                    b.HasOne("pzDatabase.model.factura", null)
                        .WithMany("pedido")
                        .HasForeignKey("facturaid");
                });

            modelBuilder.Entity("pzDatabase.model.detallePedido", b =>
                {
                    b.Navigation("pedido");
                });

            modelBuilder.Entity("pzDatabase.model.factura", b =>
                {
                    b.Navigation("pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
